import unittest

import narrative_dynamics.abm as abm


class NetworkABMPublicAPITests(unittest.TestCase):
    def test_public_api_exports_complete_v5_surface(self):
        self.assertEqual(
            set(abm.__all__),
            {
                "NetworkAgentSpec",
                "SocialEdge",
                "SocialNetwork",
                "NetworkABMModel",
                "NetworkAgentState",
                "PopulationState",
                "initialize_population",
                "InformationTransmission",
                "NetworkRoundResult",
                "PopulationTrajectory",
                "simulate_round",
                "simulate_population",
                "EmergenceMetrics",
                "measure_emergence",
                "EdgeSelector",
                "EdgeInfluenceChange",
                "BeliefSeed",
                "NetworkIntervention",
                "AppliedIntervention",
                "InterventionComparison",
                "apply_intervention",
                "compare_intervention",
                "no_propagation_intervention",
                "AdaptiveTrustModel",
                "EdgeTrustState",
                "AdaptivePopulationState",
                "TruthFeedback",
                "initialize_adaptive_population",
                "EdgeTrustUpdate",
                "AdaptiveRoundResult",
                "AdaptiveTrajectory",
                "population_view",
                "simulate_adaptive_round",
                "simulate_adaptive_population",
                "AdaptiveTrustMetrics",
                "measure_adaptive_trust",
                "LifecycleStatus",
                "LifecycleEventKind",
                "PopulationLifecycleEvent",
                "PopulationLifecycleModel",
                "LifecycleMemberState",
                "PopulationLifecycleState",
                "initialize_lifecycle_population",
                "LifecycleRoundResult",
                "LifecycleTrajectory",
                "active_population_view",
                "simulate_lifecycle_round",
                "simulate_lifecycle_population",
                "PopulationLifecycleMetrics",
                "measure_population_lifecycle",
                "EndogenousRewiringModel",
                "EdgeTopologyState",
                "RewiringPopulationState",
                "initialize_rewiring_population",
                "EdgeRewiringUpdate",
                "RewiringRoundResult",
                "RewiringTrajectory",
                "rewiring_population_view",
                "simulate_rewiring_round",
                "simulate_rewiring_population",
                "NetworkStructureMetrics",
                "measure_network_structure",
                "EvolvingNetworkModel",
                "EvolvingPopulationState",
                "initialize_evolving_population",
                "EvolvingRoundResult",
                "EvolvingTrajectory",
                "evolving_active_population_view",
                "simulate_evolving_round",
                "simulate_evolving_population",
                "EvolvingSystemMetrics",
                "measure_evolving_system",
            },
        )
        for name in abm.__all__:
            self.assertTrue(hasattr(abm, name), name)


if __name__ == "__main__":
    unittest.main()
