import json
from pathlib import Path
import unittest

import narrative_dynamics.abm as abm
from narrative_dynamics.abm import scenario_authoring_contracts as authoring_contracts
from narrative_dynamics.abm import scenario_compiler
from narrative_dynamics.abm import scenario_package
from narrative_dynamics.abm import scenario_package_contracts as package_contracts
from narrative_dynamics.abm.situated_projection import (
    project_situated_narrative as source_project_situated_narrative,
)
from narrative_dynamics.abm import situated_projection_contracts as projection_contracts
from narrative_dynamics.abm import situated_realization as realization
from narrative_dynamics.abm import situated_realization_contracts as realization_contracts
from narrative_dynamics.abm import situated_network as situated_network
from narrative_dynamics.abm import situated_network_contracts as network_contracts
from narrative_dynamics.abm import situated_spatial_map as spatial_map
from narrative_dynamics.abm import situated_spatial_map_contracts as spatial_contracts


class NetworkABMPublicAPITests(unittest.TestCase):
    def test_public_api_exports_current_v21_1_surface(self):
        self.assertEqual(
            set(abm.__all__),
            {
                "NetworkAgentSpec",
                "SocialEdge",
                "SocialNetwork",
                "NetworkABMModel",
                "NetworkAgentState",
                "PopulationState",
                "initialize_population",
                "InformationTransmission",
                "NetworkRoundResult",
                "PopulationTrajectory",
                "simulate_round",
                "simulate_population",
                "EmergenceMetrics",
                "measure_emergence",
                "EdgeSelector",
                "EdgeInfluenceChange",
                "BeliefSeed",
                "NetworkIntervention",
                "AppliedIntervention",
                "InterventionComparison",
                "apply_intervention",
                "compare_intervention",
                "no_propagation_intervention",
                "AdaptiveTrustModel",
                "EdgeTrustState",
                "AdaptivePopulationState",
                "TruthFeedback",
                "initialize_adaptive_population",
                "EdgeTrustUpdate",
                "AdaptiveRoundResult",
                "AdaptiveTrajectory",
                "population_view",
                "simulate_adaptive_round",
                "simulate_adaptive_population",
                "AdaptiveTrustMetrics",
                "measure_adaptive_trust",
                "LifecycleStatus",
                "LifecycleEventKind",
                "PopulationLifecycleEvent",
                "PopulationLifecycleModel",
                "LifecycleMemberState",
                "PopulationLifecycleState",
                "initialize_lifecycle_population",
                "LifecycleRoundResult",
                "LifecycleTrajectory",
                "active_population_view",
                "simulate_lifecycle_round",
                "simulate_lifecycle_population",
                "PopulationLifecycleMetrics",
                "measure_population_lifecycle",
                "EndogenousRewiringModel",
                "EdgeTopologyState",
                "RewiringPopulationState",
                "initialize_rewiring_population",
                "EdgeRewiringUpdate",
                "RewiringRoundResult",
                "RewiringTrajectory",
                "rewiring_population_view",
                "simulate_rewiring_round",
                "simulate_rewiring_population",
                "NetworkStructureMetrics",
                "measure_network_structure",
                "EvolvingNetworkModel",
                "EvolvingPopulationState",
                "initialize_evolving_population",
                "EvolvingRoundResult",
                "EvolvingTrajectory",
                "evolving_active_population_view",
                "simulate_evolving_round",
                "simulate_evolving_population",
                "EvolvingSystemMetrics",
                "measure_evolving_system",
                "SharingDecision",
                "RoleDecisionPolicy",
                "TruthObservation",
                "AgentActionIntent",
                "AutonomousAgentState",
                "AutonomousNetworkModel",
                "AutonomousPopulationState",
                "initialize_autonomous_population",
                "AutonomousRoundResult",
                "AutonomousTrajectory",
                "simulate_autonomous_round",
                "simulate_autonomous_population",
                "AgentAutonomyMetrics",
                "measure_agent_autonomy",
                "RoleTransitionRule",
                "RoleTransitionRecord",
                "DynamicRoleAgentState",
                "DynamicRoleModel",
                "DynamicRolePopulationState",
                "initialize_dynamic_role_population",
                "DynamicRoleRoundResult",
                "DynamicRoleTrajectory",
                "simulate_dynamic_role_round",
                "simulate_dynamic_role_population",
                "RolePopulationCount",
                "RoleDynamicsMetrics",
                "measure_role_dynamics",
                "CalibrationSplit",
                "ObservedABMSnapshot",
                "EmpiricalABMCase",
                "EmpiricalABMDataset",
                "ABMCalibrationCandidate",
                "ABMCalibrationWeights",
                "observe_dynamic_role_state",
                "apply_calibration_candidate",
                "ABMCaseCalibrationFit",
                "ABMCandidateCalibrationFit",
                "EmpiricalABMCalibrationReport",
                "calibrate_dynamic_role_model",
                "ExperimentObjective",
                "ABMExperimentArm",
                "ABMExperimentProtocol",
                "ABMExperimentCaseResult",
                "ABMExperimentArmResult",
                "CalibratedABMExperimentReport",
                "run_calibrated_abm_experiment",
                "EvidenceFact",
                "PlaceSpec",
                "PassageSpec",
                "EmbodiedAgentSpec",
                "WorldObjectSpec",
                "SituatedWorldModel",
                "AgentBodyState",
                "WorldObjectState",
                "PassageState",
                "SituatedWorldState",
                "initialize_situated_world",
                "validate_situated_state",
                "SituatedActionKind",
                "ObservationChannel",
                "SituatedActionIntent",
                "SituatedWorldEvent",
                "SituatedObservation",
                "SituatedRoundResult",
                "resolve_situated_round",
                "SituatedPerspectiveEvent",
                "SituatedEventExplanation",
                "SituatedStory",
                "initialize_situated_story",
                "advance_situated_story",
                "replay_situated_story",
                "objective_timeline",
                "perspective_timeline",
                "direct_causes",
                "causal_ancestors",
                "information_chain",
                "explain_situated_event",
                "SituatedHypothesis",
                "SituatedObservationSymbol",
                "SituatedObservationRule",
                "SituatedObservationLikelihood",
                "SituatedActionSpec",
                "SituatedHypothesisTransition",
                "SituatedGoalSpec",
                "SituatedGoalReward",
                "SituatedAgentCognitiveModel",
                "SituatedCognitiveModel",
                "SituatedAgentMindState",
                "SituatedCognitiveState",
                "initialize_situated_cognition",
                "validate_situated_cognitive_state",
                "SituatedBeliefAdmission",
                "SituatedBeliefAdmissionResult",
                "SituatedCognitiveDecision",
                "SituatedCognitiveRoundResult",
                "SituatedDecisionExplanation",
                "SituatedCognitiveTrajectory",
                "admit_situated_observations",
                "decide_situated_action",
                "simulate_situated_cognitive_round",
                "explain_situated_decision",
                "simulate_situated_cognition",
                "MemoryChannelPolicy",
                "SituatedMemoryPolicy",
                "SituatedMemoryRecord",
                "SituatedMemoryQuery",
                "SituatedMemorySearchHit",
                "SituatedMemoryWriteReport",
                "SituatedMemoryIndexReport",
                "standard_situated_memory_policy",
                "SituatedMemoryStorageError",
                "SituatedMemoryConflictError",
                "initialize_situated_memory",
                "ingest_situated_memory",
                "ingest_situated_story",
                "list_situated_memories",
                "search_situated_memories",
                "set_situated_memory_active",
                "rebuild_situated_memory_index",
                "SituatedMemoryRecallCue",
                "SituatedAgentRecallPolicy",
                "SituatedMemoryCognitiveModel",
                "initialize_situated_memory_cognition",
                "SituatedMemoryRecallAdmission",
                "SituatedMemoryRecallResult",
                "SituatedMemoryCognitiveRoundResult",
                "SituatedMemoryCognitiveTrajectory",
                "recall_situated_memories",
                "simulate_situated_memory_cognitive_round",
                "simulate_situated_memory_cognition",
                "SituatedClaimStatus",
                "SituatedSocialEvidenceKind",
                "SituatedClaimTopic",
                "SituatedSocialMemoryPolicy",
                "SituatedSocialMemoryModel",
                "SituatedSourceRelationship",
                "SituatedConsolidatedClaim",
                "SituatedSocialEvidence",
                "SituatedSocialMemoryState",
                "validate_situated_social_memory_state",
                "initialize_situated_social_memory",
                "SituatedSocialMemoryUpdate",
                "advance_situated_social_memory",
                "SituatedSocialCognitiveRoundResult",
                "SituatedSocialCognitiveTrajectory",
                "recall_situated_memories_with_social_trust",
                "simulate_situated_social_cognitive_round",
                "simulate_situated_social_cognition",
                "SituatedPerceptionLayer",
                "SituatedEdgeActivation",
                "SituatedPerceptFidelity",
                "SituatedPerceptionEdge",
                "SituatedAgentPerceptionProfile",
                "SituatedEventSignalProfile",
                "SituatedPerceptionModel",
                "SituatedPerceptionReach",
                "SituatedPercept",
                "SituatedPerceptualProjection",
                "derive_situated_perception_reach",
                "can_situated_agents_interact",
                "project_situated_percepts",
                "percepts_for_agent",
                "SituatedPerceptCognitiveRoundResult",
                "project_situated_story_percepts",
                "perceptual_timeline",
                "match_situated_percept_rule",
                "admit_situated_percepts",
                "simulate_situated_percept_cognitive_round",
                "SituatedPerceptMemoryFidelityPolicy",
                "SituatedPerceptMemoryPolicy",
                "SituatedPerceptMemoryRecord",
                "SituatedPerceptMemoryQuery",
                "SituatedPerceptMemoryHit",
                "SituatedPerceptMemoryWriteReport",
                "SituatedPerceptMemoryIndexReport",
                "standard_situated_percept_memory_policy",
                "SituatedPerceptMemoryStorageError",
                "SituatedPerceptMemoryConflictError",
                "initialize_situated_percept_memory",
                "ingest_situated_percept_story",
                "list_situated_percept_memories",
                "search_situated_percept_memories",
                "set_situated_percept_memory_active",
                "rebuild_situated_percept_memory_index",
                "SituatedPerceptMemoryCognitiveModel",
                "SituatedPerceptMemoryCognitiveRoundResult",
                "SituatedPerceptMemoryCognitiveTrajectory",
                "initialize_situated_percept_memory_cognition",
                "recall_situated_percept_memories",
                "simulate_situated_percept_memory_cognitive_round",
                "simulate_situated_percept_memory_cognition",
                "SituatedPerceptSocialCognitiveRoundResult",
                "SituatedPerceptSocialCognitiveTrajectory",
                "recall_situated_percept_memories_with_social_trust",
                "simulate_situated_percept_social_cognitive_round",
                "simulate_situated_percept_social_cognition",
                "SituatedGroundingEvidenceKind",
                "SituatedGroundingPolarity",
                "SituatedGroundingModality",
                "SituatedGroundingTemporalScope",
                "SituatedGroundingPredicate",
                "SituatedGroundingProviderIdentity",
                "SituatedSemanticGroundingModel",
                "SituatedGroundingRequest",
                "SituatedGroundingRetrievalPlan",
                "SituatedGroundingEvidence",
                "SituatedGroundingPrompt",
                "SituatedGroundedClaim",
                "SituatedSemanticGroundingArtifact",
                "SituatedStructuredLanguageProvider",
                "parse_situated_grounding_retrieval_plan",
                "build_situated_grounding_prompt",
                "validate_situated_semantic_grounding_artifact",
                "compile_situated_semantic_grounding",
                "replay_situated_semantic_grounding",
                "grounded_claims_to_situated_social_evidence",
                "NarrativeAuthority",
                "NarrativeTemporalOrder",
                "NarrativeBeatKind",
                "NarrativeBeatPhase",
                "NarrativeEntitlementScope",
                "NarrativeSupportRef",
                "NarrativeFact",
                "NarrativeEntitlement",
                "NarrativeProjectionPolicy",
                "NarrativeBeat",
                "NarrativeScene",
                "NarrativeCut",
                "NarrativeProjection",
                "project_situated_narrative",
                "NarrativeRealizationFormat",
                "NarrativeRealizationAssurance",
                "NarrativeRealizationProviderIdentity",
                "NarrativeRealizationPolicy",
                "NarrativeRealizationRequest",
                "NarrativeSceneRealizationPrompt",
                "NarrativeRealizationPrompt",
                "NarrativePassage",
                "NarrativeRealizedScene",
                "NarrativeRealizationArtifact",
                "build_narrative_realization_prompt",
                "compile_narrative_realization",
                "realize_narrative_exact_facts",
                "replay_narrative_realization",
                "render_narrative_realization_text",
                "SituatedNetworkRuntimeModel",
                "SituatedNetworkAgentNode",
                "SituatedNetworkRelationshipEdge",
                "SituatedNetworkAccessEdge",
                "SituatedNetworkTransmission",
                "SituatedNetworkSnapshot",
                "SituatedNetworkEmergenceMetrics",
                "SituatedNetworkRuntimeState",
                "SituatedNetworkRoundResult",
                "SituatedNetworkTrajectory",
                "hash_situated_percept_memory_store",
                "project_situated_network_snapshot",
                "measure_situated_network_emergence",
                "initialize_situated_network_runtime",
                "simulate_situated_network_round",
                "simulate_situated_network_runtime",
                "SpatialPlace",
                "SpatialPassage",
                "SituatedSpatialMap",
                "load_tiled_situated_spatial_map",
                "auto_layout_situated_spatial_map",
                "ScenarioDocumentRole",
                "ScenarioDocumentLocator",
                "ScenarioPackageManifest",
                "ScenarioSourceDocument",
                "ScenarioPackageSource",
                "CompiledSituatedScenario",
                "ScenarioExecutionMode",
                "ScenarioInstitution",
                "ScenarioMembership",
                "ScenarioRelationship",
                "ScenarioNormEffect",
                "ScenarioNorm",
                "ScenarioSocialWorld",
                "ScenarioPredicateKind",
                "ScenarioPredicate",
                "ScenarioSceneDependency",
                "ScenarioSceneContract",
                "ScenarioStoryAct",
                "ScenarioStoryPlan",
                "ScenarioResourceKind",
                "ScenarioKnowledgeResource",
                "ScenarioKnowledgeCatalog",
                "ScenarioAssetResource",
                "ScenarioAssetCatalog",
                "ScenarioResourceGrant",
                "ScenarioRunPolicy",
                "ScenarioCompilationError",
                "load_situated_scenario_package",
                "compile_situated_scenario_package",
                "initialize_compiled_scenario",
            },
        )
        for name in abm.__all__:
            self.assertTrue(hasattr(abm, name), name)

    def test_v17_exports_are_the_source_definitions(self):
        for name in projection_contracts.__all__:
            self.assertIs(getattr(abm, name), getattr(projection_contracts, name))
        self.assertIs(abm.project_situated_narrative, source_project_situated_narrative)

    def test_v18_exports_are_the_source_definitions(self):
        contract_names = (
            "NarrativeRealizationFormat",
            "NarrativeRealizationAssurance",
            "NarrativeRealizationProviderIdentity",
            "NarrativeRealizationPolicy",
            "NarrativeRealizationRequest",
            "NarrativeSceneRealizationPrompt",
            "NarrativeRealizationPrompt",
            "NarrativePassage",
            "NarrativeRealizedScene",
            "NarrativeRealizationArtifact",
        )
        function_names = (
            "build_narrative_realization_prompt",
            "compile_narrative_realization",
            "realize_narrative_exact_facts",
            "replay_narrative_realization",
            "render_narrative_realization_text",
        )
        for name in contract_names:
            self.assertIs(getattr(abm, name), getattr(realization_contracts, name))
        for name in function_names:
            self.assertIs(getattr(abm, name), getattr(realization, name))

    def test_v19_exports_are_the_source_definitions(self):
        for name in network_contracts.__all__:
            self.assertIs(getattr(abm, name), getattr(network_contracts, name))
        for name in situated_network.__all__:
            self.assertIs(getattr(abm, name), getattr(situated_network, name))

    def test_v20_spatial_exports_are_the_source_definitions(self):
        for name in spatial_contracts.__all__:
            self.assertIs(getattr(abm, name), getattr(spatial_contracts, name))
        for name in spatial_map.__all__:
            self.assertIs(getattr(abm, name), getattr(spatial_map, name))

    def test_v21_1_exports_are_the_source_definitions(self):
        package_contract_names = (
            "ScenarioDocumentRole",
            "ScenarioDocumentLocator",
            "ScenarioPackageManifest",
            "ScenarioSourceDocument",
            "ScenarioPackageSource",
            "CompiledSituatedScenario",
        )
        for name in package_contract_names:
            self.assertIs(getattr(abm, name), getattr(package_contracts, name))
        for name in authoring_contracts.__all__:
            self.assertIs(getattr(abm, name), getattr(authoring_contracts, name))
        self.assertIs(
            abm.load_situated_scenario_package,
            scenario_package.load_situated_scenario_package,
        )
        for name in scenario_compiler.__all__:
            self.assertIs(getattr(abm, name), getattr(scenario_compiler, name))

    def test_committed_law_firm_package_loads_and_compiles_without_a_generator(self):
        root = Path(__file__).resolve().parents[1] / "examples" / "law_firm_scenario"
        manifest = json.loads(
            (root / "scenario-package.json").read_text(encoding="utf-8")
        )
        declared_files = {item["relative_path"] for item in manifest["documents"]}
        committed_documents = {
            path.relative_to(root).as_posix()
            for path in root.rglob("*")
            if path.is_file() and path.suffix in {".json", ".tmj"}
        }
        self.assertEqual(
            committed_documents,
            declared_files | {"scenario-package.json"},
        )

        source = abm.load_situated_scenario_package(root)
        scenario = abm.compile_situated_scenario_package(source)

        self.assertEqual(source.scenario_id, "law-firm-case")
        self.assertEqual(scenario.scenario_id, "law-firm-case")
        self.assertEqual(len(source.documents), 16)
        self.assertEqual(scenario.runtime_model.model_id, "law-firm-network")


if __name__ == "__main__":
    unittest.main()
