import Browser.Interaction.AdversarialRecovery

namespace Browser.Interaction

/-- Fold a finite collection of fault requirements into one recovery action.
    `retry` is the least recovery rank and therefore the empty-set identity. -/
def aggregateRecovery : List FaultClass → RecoveryAction
  | [] => .retry
  | fault :: rest =>
      joinRecovery (minimumRecovery fault) (aggregateRecovery rest)

/-- A candidate recovery covers every fault in the finite collection. -/
def CoversFaults : List FaultClass → RecoveryAction → Prop
  | [], _ => True
  | fault :: rest, action =>
      recoveryRank (minimumRecovery fault) ≤ recoveryRank action ∧
      CoversFaults rest action

/-- The selected action covers all requirements and is no more disruptive than
    any other action that also covers them all. -/
def MinimalCombined (faults : List FaultClass) (action : RecoveryAction) : Prop :=
  CoversFaults faults action ∧
  ∀ candidate,
    CoversFaults faults candidate →
      recoveryRank action ≤ recoveryRank candidate

/-- Self-contained finite permutation relation generated by adjacent swaps. -/
inductive FaultPermutation : List FaultClass → List FaultClass → Prop where
  | nil : FaultPermutation [] []
  | cons (fault : FaultClass) {xs ys : List FaultClass} :
      FaultPermutation xs ys → FaultPermutation (fault :: xs) (fault :: ys)
  | swap (a b : FaultClass) (rest : List FaultClass) :
      FaultPermutation (a :: b :: rest) (b :: a :: rest)
  | trans {xs ys zs : List FaultClass} :
      FaultPermutation xs ys → FaultPermutation ys zs → FaultPermutation xs zs

private theorem covers_monotone
    (faults : List FaultClass) (a b : RecoveryAction)
    (hcover : CoversFaults faults a)
    (hrank : recoveryRank a ≤ recoveryRank b) :
    CoversFaults faults b := by
  induction faults with
  | nil =>
      trivial
  | cons fault rest ih =>
      rcases hcover with ⟨hfault, hrest⟩
      constructor
      · exact Nat.le_trans hfault hrank
      · exact ih hrest

/-- Adding a duplicate fault requirement does not change the aggregate. -/
theorem aggregate_duplicate_invariant
    (fault : FaultClass) (rest : List FaultClass) :
    aggregateRecovery (fault :: fault :: rest) =
      aggregateRecovery (fault :: rest) := by
  change
    joinRecovery (minimumRecovery fault)
        (joinRecovery (minimumRecovery fault) (aggregateRecovery rest)) =
      joinRecovery (minimumRecovery fault) (aggregateRecovery rest)
  rw [← join_recovery_associative]
  rw [join_recovery_idempotent]

/-- Any finite reordering generated by adjacent swaps leaves the selected
    recovery unchanged. -/
theorem aggregate_permutation_invariant
    {xs ys : List FaultClass} (h : FaultPermutation xs ys) :
    aggregateRecovery xs = aggregateRecovery ys := by
  induction h with
  | nil =>
      rfl
  | cons fault h ih =>
      simp [aggregateRecovery, ih]
  | swap a b rest =>
      change
        joinRecovery (minimumRecovery a)
            (joinRecovery (minimumRecovery b) (aggregateRecovery rest)) =
          joinRecovery (minimumRecovery b)
            (joinRecovery (minimumRecovery a) (aggregateRecovery rest))
      rw [← join_recovery_associative]
      rw [join_recovery_commutative (minimumRecovery a) (minimumRecovery b)]
      rw [join_recovery_associative]
  | trans hxy hyz ihxy ihyz =>
      exact Eq.trans ihxy ihyz

/-- The aggregate is sufficient for every member of the finite fault list. -/
theorem aggregate_covers_faults (faults : List FaultClass) :
    CoversFaults faults (aggregateRecovery faults) := by
  induction faults with
  | nil =>
      trivial
  | cons fault rest ih =>
      constructor
      · exact join_recovery_left_upper
          (minimumRecovery fault) (aggregateRecovery rest)
      · exact covers_monotone rest
          (aggregateRecovery rest)
          (joinRecovery (minimumRecovery fault) (aggregateRecovery rest))
          ih
          (join_recovery_right_upper
            (minimumRecovery fault) (aggregateRecovery rest))

/-- Any candidate that covers all faults is at least as disruptive as the
    aggregate. -/
theorem aggregate_least_upper
    (faults : List FaultClass) (candidate : RecoveryAction)
    (hcover : CoversFaults faults candidate) :
    recoveryRank (aggregateRecovery faults) ≤ recoveryRank candidate := by
  induction faults with
  | nil =>
      simp [aggregateRecovery, recoveryRank]
  | cons fault rest ih =>
      rcases hcover with ⟨hfault, hrest⟩
      exact join_recovery_least_upper
        (minimumRecovery fault)
        (aggregateRecovery rest)
        candidate
        hfault
        (ih hrest)

/-- Unified finite-fault theorem: the aggregate is exactly the least recovery
    action sufficient for the whole collection. -/
theorem aggregate_is_minimal_combined (faults : List FaultClass) :
    MinimalCombined faults (aggregateRecovery faults) := by
  constructor
  · exact aggregate_covers_faults faults
  · intro candidate hcover
    exact aggregate_least_upper faults candidate hcover

end Browser.Interaction
