"""Research simulation, calibration, validation, and model-adapter runtime."""

from narrative_dynamics.conformance import (
    ConformanceDefinitionError,
    ConformanceMismatch,
    ExactRational,
    ReferenceSuite,
    ReferenceVector,
    assert_reference_conformance,
    default_operation_evaluators,
    load_reference_suite,
)
from narrative_dynamics.contracts import (
    ExecutionCapture,
    ExperimentManifest,
    ExperimentStage,
    ModelRun,
    Scenario,
    SimulationTrace,
    SimulatorModel,
    TraceEvent,
)
from narrative_dynamics.manifest import stable_content_hash
from narrative_dynamics.process_execution import (
    CancellationToken,
    ModelCancelled,
    ModelExecutionError,
    ModelOutputLimitExceeded,
    ModelProtocolError,
    ModelRemoteError,
    ModelResourceLimitExceeded,
    ModelTimeout,
    ModelTraceLimitExceeded,
    ProcessExecutionResult,
    ProcessLimits,
    SubprocessModel,
)
from narrative_dynamics.registry import (
    ModelContract,
    ModelKind,
    ModelLifecycle,
    ModelRegistry,
    ModelSchema,
)
from narrative_dynamics.schema_validation import (
    ModelSchemaDefinitionError,
    ModelSchemaViolation,
    RUNTIME_SCHEMA_DIALECT,
    validate_schema_value,
)
from narrative_dynamics.simulation import ModelFactory, SimulationRunner

__all__ = [
    "CancellationToken",
    "ConformanceDefinitionError",
    "ConformanceMismatch",
    "ExactRational",
    "ExecutionCapture",
    "ExperimentManifest",
    "ExperimentStage",
    "ModelCancelled",
    "ModelContract",
    "ModelExecutionError",
    "ModelFactory",
    "ModelKind",
    "ModelLifecycle",
    "ModelOutputLimitExceeded",
    "ModelProtocolError",
    "ModelRegistry",
    "ModelRemoteError",
    "ModelResourceLimitExceeded",
    "ModelRun",
    "ModelSchema",
    "ModelSchemaDefinitionError",
    "ModelSchemaViolation",
    "ModelTimeout",
    "ModelTraceLimitExceeded",
    "ProcessExecutionResult",
    "ProcessLimits",
    "RUNTIME_SCHEMA_DIALECT",
    "ReferenceSuite",
    "ReferenceVector",
    "Scenario",
    "SimulationRunner",
    "SimulationTrace",
    "SimulatorModel",
    "SubprocessModel",
    "TraceEvent",
    "assert_reference_conformance",
    "default_operation_evaluators",
    "load_reference_suite",
    "stable_content_hash",
    "validate_schema_value",
]
