"""Research simulation, calibration, validation, and model-adapter runtime."""

from narrative_dynamics.conformance import (
    ConformanceDefinitionError,
    ConformanceMismatch,
    ExactRational,
    ReferenceSuite,
    ReferenceVector,
    assert_reference_conformance,
    default_operation_evaluators,
    load_reference_suite,
)
from narrative_dynamics.contracts import (
    ExecutionCapture,
    ExperimentManifest,
    ExperimentStage,
    ModelRun,
    Scenario,
    SimulationTrace,
    SimulatorModel,
    TraceEvent,
)
from narrative_dynamics.external_validation import (
    EXTERNAL_CLAIM_SCOPE,
    ExternalConstraintPlan,
    ExternalConstraintStatus,
    ExternalFinalEvaluation,
    ExternalPairwiseSeparationFinding,
    ExternalPredictiveAdequacyFinding,
    ExternalReleasePreflight,
    ExternalScoreRole,
    ExternalStratum,
    ExternalStratumScore,
    ExternalValidationConstraintError,
    ExternalValidationPreregistration,
    ExternalValidationProtocolError,
    PairwiseSeparationRule,
    PredictiveAdequacyStatus,
    PredictiveSeparationStatus,
    evaluate_external_final,
    preflight_external_releases,
)
import narrative_dynamics.external_validation as _external_validation
from narrative_dynamics.external_final_assembly import (
    assemble_external_final_from_reports as _assemble_external_final_from_reports,
)

_external_validation.assemble_external_final_from_reports = (
    _assemble_external_final_from_reports
)
if "assemble_external_final_from_reports" not in _external_validation.__all__:
    _external_validation.__all__.append("assemble_external_final_from_reports")

from narrative_dynamics.external_prediction import (
    ExternalFinalPredictionArtifact,
    ExternalModelPrediction,
    ExternalSeedPrediction,
    predict_external_final_once,
    score_external_prediction_artifact,
)
from narrative_dynamics.losses import (
    DEFAULT_METRIC_LOSS,
    CategoricalBrierLoss,
    CategoricalLogLoss,
    CategoricalMetricGroup,
    MetricLoss,
    WeightedSquaredErrorLoss,
    evaluate_metric_loss,
    metric_loss_identity,
)
from narrative_dynamics.measurement_validity import (
    ExactInvarianceFinding,
    MEASUREMENT_CLAIM_SCOPE,
    MeasurementAggregation,
    MeasurementAuditAttempt,
    MeasurementAuditCase,
    MeasurementAuditInput,
    MeasurementDependenceFinding,
    MeasurementScore,
    MeasurementTerminalClass,
    MeasurementValidityReport,
    MeasurementValidityProtocol,
    MeasurementValidityStatus,
    classify_material_reversal,
    evaluate_categorical_coordinate_invariance,
    measurement_report_payload,
    permute_binary_metric_map,
)
from narrative_dynamics.manifest import stable_content_hash
from narrative_dynamics.observations import (
    OBSERVATION_DATASET_SCHEMA_VERSION,
    EXTERNAL_EVIDENCE_ORIGIN,
    AdequacyThresholds,
    AlternativeModelComparisonReport,
    AlternativeModelEvaluation,
    CategoricalTargetPlan,
    CategoricalTargetSpec,
    ComparisonPreregistration,
    ConstructedObservationCase,
    ConstructedTargetSet,
    ExternalEvidenceDeclaration,
    ExternalValidationError,
    FrozenModelCandidate,
    FrozenModelSpec,
    ObservationCase,
    ObservationDataset,
    ObservationPartition,
    ObservationPartitionRole,
    ObservationRecord,
    PreregisteredEvaluationProtocol,
    ProtocolRelease,
    ProtocolReleaseVerificationError,
    ReleasedModelComparisonReport,
    TargetConstructionReport,
    TrainingCandidateFit,
    TrainingCaseFit,
    TrainingFitReport,
    VerifiedProtocolRelease,
    WitnessReceipt,
    compare_registered_models,
    compare_released_models,
    construct_categorical_targets,
    fit_training_target_grid,
    load_observation_dataset,
    verify_protocol_release,
)
from narrative_dynamics.model_comparison import (
    ComparisonModel,
    ModelComparisonEntry,
    ModelComparisonReport,
    compare_models_on_final_partition,
)
from narrative_dynamics.process_execution import (
    CancellationToken,
    ModelCancelled,
    ModelExecutionError,
    ModelOutputLimitExceeded,
    ModelProtocolError,
    ModelRemoteError,
    ModelResourceLimitExceeded,
    ModelTimeout,
    ModelTraceLimitExceeded,
    ProcessExecutionResult,
    ProcessLimits,
    SubprocessModel,
)
from narrative_dynamics.registry import (
    ModelContract,
    ModelKind,
    ModelLifecycle,
    ModelRegistry,
    ModelSchema,
)
from narrative_dynamics.schema_validation import (
    ModelSchemaDefinitionError,
    ModelSchemaViolation,
    RUNTIME_SCHEMA_DIALECT,
    validate_schema_value,
)
from narrative_dynamics.simulation import ModelFactory, SimulationRunner

__all__ = [
    "OBSERVATION_DATASET_SCHEMA_VERSION",
    "EXTERNAL_CLAIM_SCOPE",
    "EXTERNAL_EVIDENCE_ORIGIN",
    "AdequacyThresholds",
    "AlternativeModelComparisonReport",
    "AlternativeModelEvaluation",
    "CancellationToken",
    "CategoricalBrierLoss",
    "CategoricalLogLoss",
    "CategoricalMetricGroup",
    "CategoricalTargetPlan",
    "CategoricalTargetSpec",
    "ComparisonModel",
    "ComparisonPreregistration",
    "ConformanceDefinitionError",
    "ConformanceMismatch",
    "ConstructedObservationCase",
    "ConstructedTargetSet",
    "DEFAULT_METRIC_LOSS",
    "ExactRational",
    "ExecutionCapture",
    "ExactInvarianceFinding",
    "ExperimentManifest",
    "ExperimentStage",
    "ExternalConstraintPlan",
    "ExternalConstraintStatus",
    "ExternalEvidenceDeclaration",
    "ExternalFinalEvaluation",
    "ExternalFinalPredictionArtifact",
    "ExternalModelPrediction",
    "ExternalPairwiseSeparationFinding",
    "ExternalPredictiveAdequacyFinding",
    "ExternalReleasePreflight",
    "ExternalScoreRole",
    "ExternalSeedPrediction",
    "ExternalStratum",
    "ExternalStratumScore",
    "ExternalValidationConstraintError",
    "ExternalValidationError",
    "ExternalValidationPreregistration",
    "ExternalValidationProtocolError",
    "FrozenModelCandidate",
    "FrozenModelSpec",
    "MetricLoss",
    "MEASUREMENT_CLAIM_SCOPE",
    "MeasurementAggregation",
    "MeasurementAuditAttempt",
    "MeasurementAuditCase",
    "MeasurementAuditInput",
    "MeasurementDependenceFinding",
    "MeasurementScore",
    "MeasurementTerminalClass",
    "MeasurementValidityReport",
    "MeasurementValidityProtocol",
    "MeasurementValidityStatus",
    "ModelCancelled",
    "ModelComparisonEntry",
    "ModelComparisonReport",
    "ModelContract",
    "ModelExecutionError",
    "ModelFactory",
    "ModelKind",
    "ModelLifecycle",
    "ModelOutputLimitExceeded",
    "ModelProtocolError",
    "ModelRegistry",
    "ModelRemoteError",
    "ModelResourceLimitExceeded",
    "ModelRun",
    "ModelSchema",
    "ModelSchemaDefinitionError",
    "ModelSchemaViolation",
    "ModelTimeout",
    "ModelTraceLimitExceeded",
    "ObservationCase",
    "ObservationDataset",
    "ObservationPartition",
    "ObservationPartitionRole",
    "ObservationRecord",
    "PairwiseSeparationRule",
    "PredictiveAdequacyStatus",
    "PredictiveSeparationStatus",
    "PreregisteredEvaluationProtocol",
    "ProcessExecutionResult",
    "ProcessLimits",
    "ProtocolRelease",
    "ProtocolReleaseVerificationError",
    "RUNTIME_SCHEMA_DIALECT",
    "ReferenceSuite",
    "ReferenceVector",
    "ReleasedModelComparisonReport",
    "Scenario",
    "SimulationRunner",
    "SimulationTrace",
    "SimulatorModel",
    "SubprocessModel",
    "TargetConstructionReport",
    "TraceEvent",
    "TrainingCandidateFit",
    "TrainingCaseFit",
    "TrainingFitReport",
    "VerifiedProtocolRelease",
    "WeightedSquaredErrorLoss",
    "WitnessReceipt",
    "assert_reference_conformance",
    "compare_models_on_final_partition",
    "compare_registered_models",
    "compare_released_models",
    "classify_material_reversal",
    "construct_categorical_targets",
    "default_operation_evaluators",
    "evaluate_external_final",
    "evaluate_categorical_coordinate_invariance",
    "evaluate_metric_loss",
    "fit_training_target_grid",
    "load_observation_dataset",
    "load_reference_suite",
    "metric_loss_identity",
    "measurement_report_payload",
    "predict_external_final_once",
    "preflight_external_releases",
    "permute_binary_metric_map",
    "score_external_prediction_artifact",
    "stable_content_hash",
    "validate_schema_value",
    "verify_protocol_release",
]

from narrative_dynamics.external_validation import (
    ExternalConstraintCandidateLoss,
    ExternalConstraintFinding,
    ExternalCoordinateConstraint,
    evaluate_external_constraint,
)

__all__ += [
    "ExternalConstraintCandidateLoss",
    "ExternalConstraintFinding",
    "ExternalCoordinateConstraint",
    "evaluate_external_constraint",
]

from narrative_dynamics.external_validation import (
    ExternalValidationReport,
    ExternalValidationReportError,
    build_external_validation_report,
)

__all__ += [
    "ExternalValidationReport",
    "ExternalValidationReportError",
    "build_external_validation_report",
]
